
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int SMALLER_EQUAL = 25;
  public static final int ELSE = 7;
  public static final int SMALLER = 23;
  public static final int CHARACTERS = 26;
  public static final int EQUAL = 2;
  public static final int THEN = 6;
  public static final int WHILE = 11;
  public static final int TERMINATOR = 14;
  public static final int IDENTIFIER = 27;
  public static final int RETURN = 15;
  public static final int GREATER_EQUAL = 24;
  public static final int NOT_EQUAL = 21;
  public static final int GREATER = 22;
  public static final int IF = 5;
  public static final int SEPARATOR = 12;
  public static final int COLON = 8;
  public static final int ADD_SUB = 18;
  public static final int CURLY_BRACKETS_RIGTH = 10;
  public static final int DOUBLE_EQUAL = 20;
  public static final int NUMBER = 28;
  public static final int EOF = 0;
  public static final int BRACKETS_RIGTH = 4;
  public static final int CURLY_BRACKETS_LEFT = 9;
  public static final int PRINT = 16;
  public static final int error = 1;
  public static final int ARROW = 13;
  public static final int MULT_DIV = 19;
  public static final int BOOLEAN_VALUE = 29;
  public static final int UNDEFINED = 17;
  public static final int BRACKETS_LEFT = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EQUAL",
  "BRACKETS_LEFT",
  "BRACKETS_RIGTH",
  "IF",
  "THEN",
  "ELSE",
  "COLON",
  "CURLY_BRACKETS_LEFT",
  "CURLY_BRACKETS_RIGTH",
  "WHILE",
  "SEPARATOR",
  "ARROW",
  "TERMINATOR",
  "RETURN",
  "PRINT",
  "UNDEFINED",
  "ADD_SUB",
  "MULT_DIV",
  "DOUBLE_EQUAL",
  "NOT_EQUAL",
  "GREATER",
  "SMALLER",
  "GREATER_EQUAL",
  "SMALLER_EQUAL",
  "CHARACTERS",
  "IDENTIFIER",
  "NUMBER",
  "BOOLEAN_VALUE"
  };
}

